### ISSUE TITLE
Support for Slim 3.1

### ISSUE THREAD

**Issue by masrodjie** [juliangut/slim-doctrine#4]
Is it support for Slim 3.1?
I was tried to install using composer with Slim 3.1, and got error:
  Problem 1
    - Can only install one of: slim/slim[3.0.0, 3.1.0].
    - Can only install one of: slim/slim[3.1.0, 3.0.0].
    - Can only install one of: slim/slim[3.0.0, 3.1.0].
    - juliangut/slim-doctrine 0.6 requires slim/slim 3.0 -> satisfiable by slim/slim[3.0.0].
    - Installation request for juliangut/slim-doctrine ^0.6.0 -> satisfiable by juliangut/slim-doctrine[0.6].
    - Installation request for slim/slim == 3.1.0.0 -> satisfiable by slim/slim[3.1.0].

**Comment by juliangut** [comment]
Hello masrodjie
I've released a new version with slim/slim:^3.0 as dependency, you should not get that error anymore

**Comment by masrodjie** [comment]
Previously i am using composer.json "juliangut/slim-doctrine": "^0.6.0"
And i changed it to ^0.7.0 and it's works.
Thanks
