### ISSUE TITLE
Suport doctrine couchdb

### ISSUE THREAD

**Issue by brenodouglas** [juliangut/slim-doctrine#5]
What you the idea of support for doctrine [Couchdb](http://github.com/doctrine/couchdb-odm)?

**Comment by juliangut** [comment]
Actually I was thinking about integrating it and started having a look at counchdb-odm API, and as far as I've seen it will require some changes on the ODM building and management, but I'm onto it

**Comment by juliangut** [comment]
Have a look at version 2.0-rc.1which supports couchdb and adds several improvements

**Comment by juliangut** [comment]
Tough I've to admit doctrine support for CouchDB is not that good... as long as it has been added to v2.0 (released) we might close this issue
