### ISSUE TITLE
doctrine/orm dependency

### ISSUE THREAD

**Issue by yethee** [juliangut/slim-doctrine#6]
This library requires doctrine/orm, will always be installed. Can be omit this dependency?

**Comment by juliangut** [comment]
If you plan to use only mongdb-odm I can see that as a problem, in my use cases I always make use of orm and additionally/occasionally odm

**Comment by juliangut** [comment]
Version 2 (currently 2.0-rc.1) does not force you to include ORM, it has several additions and improvements as well

**Comment by yethee** [comment]
Thanks! I'll try to use it in the coming days.

What you think about ability to auto-register services into the container?

**Comment by juliangut** [comment]
I'm no fan of _magic configurations_ and there is already a little magic in the configuration right now (see below)

I prefer to clearly state DI configuration (services) the same way you should do with class dependencies, so you know where things are coming from

(copied from Readme)

```
If no name provided for a manager a default one will be given:

* entityManager for entity_manager
* mongoDocumentManager for mongodb_document_manager
* couchDocumentManager for couchdb_document_manager
```

This is to ease configuration of the _normal_ use case, which is to have only one entity/document manager per project

**Comment by juliangut** [comment]
Can we close this @yethee ?

**Comment by yethee** [comment]
Yes, 2.0-rc2 and 2.0 are work for me.
Thanks!

Sorry for late feedback.
